FROM bethgelab/jupyter-torch:ubuntu-14.04

RUN pip2 --no-cache-dir install -U Pillow
RUN pip2 --no-cache-dir install -U captcha
RUN pip2 --no-cache-dir install -U keras
RUN pip2 --no-cache-dir install -U pandas
